# Generated by Django 4.2.7 on 2023-11-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='expiry',
            field=models.DateField(null=True),
        ),
    ]
