# Generated by Django 4.2.7 on 2023-11-11 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadpp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadpp',
            old_name='desciption',
            new_name='description',
        ),
    ]
